version: '3.8'

services:
  db:
    image: postgres:15
    container_name: guexi-postgres
    restart: always
    environment:
      POSTGRES_USER: guexi
      POSTGRES_PASSWORD: guexi_pass
      POSTGRES_DB: guexi_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
